FMT - now installs, uninstalls and runs from system locations
Update: Linux
* can run multiple instances separated by [-n NAME]
* allows for custom data locations with [ -p PATH ]
* each instance has its own fmt.ini file
* allows for custom rigctrl location using --with-rigctl=[PATH]
* consolidated fmtparams.py into --> fmtmain.py
* updated autotools
* added / updated manpage generation
* tested on Py-2.7.11 / Py-3.4.3

TODO: Linux
* Add m4 module to check Python modules: Pmw, PySerial, PyAudio
* Update user guide
* move fmt binaries and libfmt to their own subdir for $(MAKE)



git-svn-id: svn://svn.code.sf.net/p/wsjt/wsjt/branches/fmt@6832 ab8295b8-cf94-4d9e-aec4-7959e3be5d79

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2609,7 +2609,7 @@ MANDIR="$MANDIR"
 LOGNAME="$LOGNAME"
 DOCSRC=$(exec pwd)/doc/user_guide
 THEMEDIR=$(exec pwd)/doc/theme/pyfmt
-DOCCONF=$(exec pwd)/doc/pyfmtr.conf
+DOCCONF=$(exec pwd)/doc/pyfmt.conf
 DOCPATH=$(exec pwd)/doc/
 LOGNAME="$LOGNAME"
 
@@ -6902,11 +6902,29 @@ if test "$HAVE_PY3" = "no"; then
 fi
 
 # ------------------------------------------------------------------------------
+#  report rigctl
+# ------------------------------------------------------------------------------
+if test ${HAVE_RGC} = "no"; then
+	echo "CONFIGURATION ERROR"
+	echo
+	echo "Hamlib Rig Control ti run $PACKAGE_NAME"
+	echo
+	echo "Possible Solutions:"
+	echo "1 Install your distro version of: libhamlib-utils"
+	echo "2 configure --with-rigctl=Path"
+	echo
+	echo 'Example:'
+	echo "./autogen.sh --with-rigctl=/home/$USER/jtsdk/hamlib3/bin/rigctl"
+	echo
+	exit 1
+fi
+
+# ------------------------------------------------------------------------------
 #  report samplerate
 # ------------------------------------------------------------------------------
 
 if test ${HAVE_SAMPLERATE} -eq 1; then
-	srstatus="OK"
+	sr_status="OK"
 else
 	echo "CONFIGURATION ERROR"
 	echo
@@ -6928,7 +6946,7 @@ fi
 # ------------------------------------------------------------------------------
 
 if test ${HAVE_FFTW3_LIB} -eq 1; then
-	ffstatus="OK"
+	ff_status="OK"
 else
 	echo "CONFIGURATION ERROR"
 	echo
@@ -6948,7 +6966,7 @@ fi
 # ------------------------------------------------------------------------------
 
 if test ${HAVE_PORTAUDIO} -eq 1; then
-	pastatus="OK"
+	pa_status="OK"
 else
 	echo "CONFIGURATION ERROR"
 	echo
@@ -6960,26 +6978,6 @@ else
 	echo
 	echo './configure CPPFLAGS="-I/path/to/portaudio/include" \'
 	echo 'LIBDIR="/path/to/portaudio/lib"'
-	echo
-	exit 1
-fi
-
-# ------------------------------------------------------------------------------
-#  report rigctl
-# ------------------------------------------------------------------------------
-if test ${HAVE_RGC} = "yes"; then
-	srstatus="OK"
-else
-	echo "CONFIGURATION ERROR"
-	echo
-	echo "Hamlib Rig Control ti run $PACKAGE_NAME"
-	echo
-	echo "Possible Solutions:"
-	echo "1 Install your distro version of: libhamlib-utils"
-	echo "2 configure --with-rigctl=Path"
-	echo
-	echo 'Example:'
-	echo "./autogen.sh --with-rigctl=/home/$USER/jtsdk/hamlib3/bin/rigctl"
 	echo
 	exit 1
 fi
@@ -8178,11 +8176,11 @@ echo "-------------------------------------------"
 echo ''
 echo " Package .........: ${PROGRAM} ${VERSION}"
 echo " Install prefix ..: ${PREFIX}"
-echo " Rigctl: .........: ${RIGCTL}"
+echo " Rig Control......: ${RIGCTL}"
 echo " Fcompiler: ......: ${FC}"
 echo " FC Lib Path .....: ${FC_LIB_PATH}"
-echo " FFTW3 ...........: ${ffstatus}"
-echo " Portaudio .......: ${pastatus}"
+echo " FFTW3 ...........: ${ff_status}"
+echo " Portaudio .......: ${pa_status}"
 echo " Copyright........: ${COPYRIGHT}"
 echo " Website .........: ${WEB}"
 echo " Report Bugs To ..: ${BUGS}"
